Correct solution for Homework 3 Question 5
input-output-hk/haskell-course pull request #8
Opened 2022-09-19 13:56 UTC by socathie

The question said sum of squares, alternatively can also change the question to say square root instead

2022-09-22 19:43 UTC, rober-m requested changes
Yes, you're right! But do you mind changing the question instead? I could do it myself, but I rather have you as the author of the contribution.

2022-09-23 03:48 UTC, socathie commented
> Yes, you're right! But do you mind changing the question instead? I could do it myself, but I rather have you as the author of the contribution.

Done! added a new commit to the same branch

2022-09-23 09:40 UTC, rober-m approved these changes

2022-09-23 09:41 UTC, merged

2022-09-23 09:41 UTC, rober-m commented
Thank you!